baseURL = "/"
languageCode = "en-us"
title = "Tremor"
theme = "tremor"
description = "Tremor is an early stage event processing system for unstructured data with rich support for structural pattern matching, filtering and transformation"
Paginate = 6

# pygmentsUseClassic            = false
# pygmentsCodeFences            = true
# pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses            = false
# pygmentsStyle                 = "monokai"

[Params]
  RSSLink = "/index.xml"
  author = "The Tremor Team" # add your company name
  github = "wayfair-tremor" # add your github profile name
  twitter = "TremorDEBS" # add your twitter profile
  email = "#"

[[menu.main]]
    name = "Documentation"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"

[markup.goldmark.renderer]
unsafe = true



[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
